#!/usr/bin/env python3
"""Does the wheel harness still meet the I2C timing spec at 400 kHz?

The pads sit at the end of a metre or so of harness, and every centimetre adds
capacitance. A bus segment is a pull-up resistor charging that capacitance, so
the rise time is RC. The I2C specification caps it.

Limits, NXP UM10204 Rev 7.0 (1 October 2021), Table 10:
    Fast-mode (400 kbit/s):  tr <= 300 ns, Cb <= 400 pF per line
    Standard-mode (100 kbit/s): tr <= 1000 ns, Cb <= 400 pF
Rise time is measured 0.3 VDD -> 0.7 VDD, so for an RC charge to VDD
    tr = R * C * ln(0.7 / 0.3) = 0.8473 * R * C
and therefore  Rp(max) = tr_limit / (0.8473 * Cb).
Rp(min) comes from the sink current the driver can pull at VOL:
    Rp(min) = (VDD - VOL) / IOL

Cable capacitance is an ASSUMPTION until measured: `--cpm` (pF per metre).
Measure the real number with an LCR meter on the finished harness, or from the
rise time on a scope, and re-run.

    python3 i2c_bus.py                        # table for the default harness
    python3 i2c_bus.py --len 1.5 --pads 8     # a longer branch
    python3 i2c_bus.py --spice out.cir        # ngspice netlist for the same case
"""
import argparse
import math

LN = math.log(0.7 / 0.3)            # 0.8473
TR_FAST, TR_STD = 300e-9, 1000e-9   # UM10204 Table 10
CB_MAX = 400e-12

def rise_time(r, c):
    return LN * r * c

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--len", type=float, default=1.0, help="harness length of one branch, m")
    ap.add_argument("--cpm", type=float, default=60.0, help="ASSUMED cable capacitance, pF/m (measure it)")
    ap.add_argument("--pads", type=int, default=1, help="devices on the enabled segment")
    ap.add_argument("--cdev", type=float, default=10.0, help="capacitance per device pin, pF")
    ap.add_argument("--cmux", type=float, default=12.0, help="multiplexer channel pin capacitance, pF")
    ap.add_argument("--vdd", type=float, default=3.3)
    ap.add_argument("--vol", type=float, default=0.4)
    ap.add_argument("--iol", type=float, default=3e-3, help="sink current at VOL, A")
    ap.add_argument("--spice", metavar="FILE", help="write an ngspice netlist")
    a = ap.parse_args()

    cb = (a.len * a.cpm + a.pads * a.cdev + a.cmux) * 1e-12
    rp_min = (a.vdd - a.vol) / a.iol
    rp_max_fast = TR_FAST / (LN * cb)
    rp_max_std = TR_STD / (LN * cb)

    print(f"Segment: {a.len:.2f} m, {a.pads} device(s)")
    print(f"  bus capacitance Cb   = {cb*1e12:6.1f} pF   (limit {CB_MAX*1e12:.0f} pF)"
          f"{'  OVER LIMIT' if cb > CB_MAX else ''}")
    print(f"  Rp(min) at VOL       = {rp_min:6.0f} ohm   (VDD {a.vdd} V, VOL {a.vol} V, IOL {a.iol*1e3:.1f} mA)")
    print(f"  Rp(max) 400 kHz      = {rp_max_fast:6.0f} ohm")
    print(f"  Rp(max) 100 kHz      = {rp_max_std:6.0f} ohm")
    print()
    print(f"  {'Rp':>8}  {'tr':>9}  {'400 kHz':>9}  {'100 kHz':>9}  {'I sink':>8}")
    for rp in (1000, 2200, 3300, 4700, 10000):
        tr = rise_time(rp, cb)
        isink = (a.vdd - a.vol) / rp * 1e3
        print(f"  {rp:8.0f}  {tr*1e9:7.0f} ns  {'PASS' if tr <= TR_FAST else 'FAIL':>9}"
              f"  {'PASS' if tr <= TR_STD else 'FAIL':>9}  {isink:6.2f} mA")
    print("\n  PASS/FAIL against UM10204 Rev 7.0 Table 10 (tr <= 300 ns fast, <= 1 us standard).")
    print("  Cb is an estimate until the harness is measured: --cpm is an assumption.")

    if a.spice:
        net = f"""* I2C bus segment rise time, generated by i2c_bus.py
* harness {a.len} m, {a.pads} device(s), Cb = {cb*1e12:.1f} pF
.param rp=4700
Vdd vdd 0 DC {a.vdd}
Rp  vdd sda {{rp}}
Cb  sda 0 {cb*1e12:.1f}p
* open-drain driver: pulls low, then releases at t = 1 us
Sw  sda 0 gate 0 sw
Vg  gate 0 PULSE(1 0 1u 1n 1n 5u 10u)
.model sw SW(Ron=20 Roff=1e9 Vt=0.5)
.tran 5n 12u
.control
run
meas tran t30 WHEN v(sda)={0.3*a.vdd:.3f} RISE=1
meas tran t70 WHEN v(sda)={0.7*a.vdd:.3f} RISE=1
let tr = t70 - t30
print tr
.endc
.end
"""
        with open(a.spice, "w") as f:
            f.write(net)
        print(f"\n  wrote {a.spice} - run it with:  ngspice -b {a.spice}")

if __name__ == "__main__":
    main()
