-- Smart Wheel - APPLY EVERYTHING (Team 18, generated 2026-09-25)
--
-- Brings a database to exactly the state the app and the website expect.
-- It is the seven migrations, in order, in one file:
--   schema -> live -> v3_dashboard -> v4_flags -> v5_delete -> v6_quality -> v7_history
--
-- Safe to run on a database that already has some or all of it: every
-- statement is written to be re-runnable (create ... if not exists, create or
-- replace, drop policy ... if exists before create).
--
-- It does NOT touch public.test_readings, the team's original table.
--
-- How to run: Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
-- Generated by build_apply_all.py; edit the migrations, not this file.

begin;


-- ===================================================================
-- schema.sql
-- ===================================================================

-- Smart Wheel — Supabase schema
--
-- Run this in the Supabase dashboard: SQL Editor → New query → paste → Run.
--
-- Primary keys are UUIDs generated on the phone, NOT database defaults. That is
-- deliberate: a drive is recorded offline and uploaded later, so the id must
-- exist before the row ever reaches Postgres. It also makes uploads idempotent —
-- re-sending after a failed sync upserts the same row instead of duplicating it.

-- ---------------------------------------------------------------- profiles --
create table if not exists public.driver_profiles (
  id            uuid primary key,
  custom_id     text,                    -- team-assigned code, e.g. SUBJ-001
  display_name  text not null,
  weight_kg     numeric(5,2),
  age           integer check (age is null or (age > 0 and age < 130)),
  height_cm     numeric(5,2),
  gender        text check (
                  gender is null
                  or gender in ('male','female','other','prefer_not_to_say')
                ),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_profiles_custom_id
  on public.driver_profiles (custom_id);

-- ---------------------------------------------------------------- sessions --
create table if not exists public.drive_sessions (
  id               uuid primary key,
  profile_id       uuid not null references public.driver_profiles (id)
                     on delete cascade,
  started_at       timestamptz not null,
  ended_at         timestamptz,
  -- Stored rather than derived so reports and charts need no date arithmetic.
  duration_seconds integer,
  status           text not null default 'completed',
  uploaded_at      timestamptz not null default now()
);

create index if not exists idx_sessions_profile
  on public.drive_sessions (profile_id);
create index if not exists idx_sessions_started
  on public.drive_sessions (started_at desc);

-- --------------------------------------------------------------- telemetry --
-- One row per sample. Storing every reading rather than a summary is what lets
-- the dashboard draw a real time series and lets stats be recomputed later.
create table if not exists public.telemetry_events (
  id              uuid primary key,
  session_id      uuid not null references public.drive_sessions (id)
                    on delete cascade,
  sequence_number integer,
  event_type      text not null,          -- 'ping' | 'vitals'
  bpm             integer,
  spo2            integer,
  signal_quality  integer,
  battery         integer,
  -- Measured by the phone on arrival. The wheel's own clock is not trusted.
  received_at     timestamptz not null,
  uploaded_at     timestamptz not null default now(),
  -- The wheel's sequence numbers restart when it reboots, so uniqueness is
  -- scoped per session. This is what makes a repeated upload harmless.
  unique (session_id, sequence_number)
);

create index if not exists idx_telemetry_session
  on public.telemetry_events (session_id);
create index if not exists idx_telemetry_received
  on public.telemetry_events (session_id, received_at);

-- ------------------------------------------------------- convenience views --
-- Per-session physiological summary, for the dashboard.
-- dropped first: a later migration changes the columns, and
-- "create or replace view" cannot remove a column on a re-run.
drop view if exists public.session_summaries;
create view public.session_summaries as
select
  s.id                         as session_id,
  s.profile_id,
  p.display_name,
  p.custom_id,
  s.started_at,
  s.ended_at,
  s.duration_seconds,
  count(e.bpm)                 as samples,
  min(e.bpm)                   as bpm_min,
  max(e.bpm)                   as bpm_max,
  round(avg(e.bpm), 1)         as bpm_avg,
  min(e.spo2)                  as spo2_min,
  max(e.spo2)                  as spo2_max,
  round(avg(e.spo2), 1)        as spo2_avg
from public.drive_sessions s
join public.driver_profiles p on p.id = s.profile_id
left join public.telemetry_events e on e.session_id = s.id
group by s.id, p.display_name, p.custom_id;

-- ------------------------------------------------------------------- RLS ---
-- Supabase exposes tables through PostgREST using the publishable/anon key,
-- which ships inside the mobile app and must be treated as public. Row Level
-- Security is therefore the ONLY thing standing between that key and your data.
--
-- The policies below are permissive: they let any anon caller read and write.
-- That is acceptable for a closed prototype but is NOT safe for real subject
-- data — anyone who extracts the key from the app can read every record.
--
-- Before collecting real physiological data, add authentication and replace
-- these with per-user policies (e.g. `auth.uid() = owner_id`).
alter table public.driver_profiles  enable row level security;
alter table public.drive_sessions   enable row level security;
alter table public.telemetry_events enable row level security;

drop policy if exists prototype_all on public.driver_profiles;
create policy prototype_all on public.driver_profiles
  for all to anon, authenticated using (true) with check (true);

drop policy if exists prototype_all on public.drive_sessions;
create policy prototype_all on public.drive_sessions
  for all to anon, authenticated using (true) with check (true);

drop policy if exists prototype_all on public.telemetry_events;
create policy prototype_all on public.telemetry_events
  for all to anon, authenticated using (true) with check (true);


-- ===================================================================
-- live.sql
-- ===================================================================

-- Smart Wheel — live dashboard support. Run AFTER schema.sql
-- (Supabase dashboard: SQL Editor → New query → paste → Run). Safe to re-run.

-- 1. Realtime: broadcast new rows so the website updates without refreshing.
do $$
declare t text;
begin
  foreach t in array array['drive_sessions', 'telemetry_events'] loop
    if not exists (select 1 from pg_publication_tables
                   where pubname = 'supabase_realtime'
                     and schemaname = 'public' and tablename = t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- 2. Bridge for the current website, which only reads public.test_readings
--    (value, device_name). Every usable reading the phone uploads is mirrored
--    there as two rows: "<subject> BPM" and "<subject> SpO2".
--    Any failure here is swallowed: the mirror must never block the real
--    telemetry insert. Remove with:
--      drop trigger if exists mirror_to_test_readings on public.telemetry_events;
create or replace function public.mirror_to_test_readings()
returns trigger language plpgsql security definer set search_path = public as $$
declare who text;
begin
  if new.bpm is null or new.spo2 is null then return new; end if;
  select coalesce(nullif(p.custom_id, ''), p.display_name) into who
    from drive_sessions s join driver_profiles p on p.id = s.profile_id
   where s.id = new.session_id;
  begin
    insert into test_readings (value, device_name)
    values (new.bpm,  coalesce(who, 'wheel') || ' BPM'),
           (new.spo2, coalesce(who, 'wheel') || ' SpO2');
  exception when others then
    raise warning 'mirror_to_test_readings skipped: %', sqlerrm;
  end;
  return new;
end $$;

drop trigger if exists mirror_to_test_readings on public.telemetry_events;
create trigger mirror_to_test_readings
  after insert on public.telemetry_events
  for each row execute function public.mirror_to_test_readings();


-- ===================================================================
-- v3_dashboard.sql
-- ===================================================================

-- Smart Wheel — v3: live dashboard, robust session stats, baselines, archives.
--
-- Run AFTER schema.sql and live.sql (SQL Editor → New query → paste → Run).
-- Safe to re-run: every statement is idempotent.
--
-- What this adds
--   * drive_sessions heartbeat (last_seen_at, link_state) so the dashboard can
--     tell "driving, sensor on" from "phone went quiet" without guessing.
--   * telemetry_events.finger / quality, so "no finger on the wheel" is visible.
--   * session_summaries v2: realistic low/high (5th/95th percentile) next to
--     the absolute min/max, which a single motion artifact can distort.
--   * driver_baselines: each driver's usual range from their finished drives
--     (proposal: baseline comparison per user profile).
--   * session_archives + the private 'session-archives' Storage bucket for the
--     compressed full-waveform "folded" archive (opt-in; see docs/ARCHIVE_FORMAT.md).
--   * Removes the test_readings bridge from live.sql: the dashboard now reads
--     the real tables directly.

-- --------------------------------------------------------------- sessions --
alter table public.drive_sessions add column if not exists last_seen_at   timestamptz;
alter table public.drive_sessions add column if not exists link_state     text;      -- 'streaming' | 'sensor_lost' | 'pi_lost'
alter table public.drive_sessions add column if not exists storage_mode   text not null default 'vitals'; -- 'vitals' | 'full'
alter table public.drive_sessions add column if not exists sample_rate_hz integer;

create index if not exists idx_sessions_active
  on public.drive_sessions (status, last_seen_at desc);

-- -------------------------------------------------------------- telemetry --
alter table public.telemetry_events add column if not exists finger  boolean;
alter table public.telemetry_events add column if not exists quality smallint;       -- 0..100 periodicity score from the ESP32

-- ------------------------------------------------------ session summaries --
-- Percentiles, not just min/max: PPG on a steering wheel picks up motion and
-- grip artifacts, and one bad second would otherwise define the "lowest" or
-- "highest" heart rate of a whole drive. p05/p95 are the realistic range;
-- min/max stay available for completeness.
drop view if exists public.session_summaries;
create view public.session_summaries
with (security_invoker = true) as
select
  s.id                                                        as session_id,
  s.profile_id,
  p.display_name,
  p.custom_id,
  s.started_at,
  s.ended_at,
  s.duration_seconds,
  s.status,
  s.storage_mode,
  s.last_seen_at,
  count(e.id)                                                 as frames,
  count(e.bpm)                                                as samples,
  round(100.0 * count(e.bpm) / nullif(count(e.id), 0), 1)     as usable_pct,
  min(e.bpm)                                                  as bpm_min,
  max(e.bpm)                                                  as bpm_max,
  round(avg(e.bpm), 1)                                        as bpm_avg,
  percentile_cont(0.05) within group (order by e.bpm)         as bpm_p05,
  percentile_cont(0.50) within group (order by e.bpm)         as bpm_median,
  percentile_cont(0.95) within group (order by e.bpm)         as bpm_p95,
  min(e.spo2)                                                 as spo2_min,
  max(e.spo2)                                                 as spo2_max,
  round(avg(e.spo2), 1)                                       as spo2_avg,
  percentile_cont(0.05) within group (order by e.spo2)        as spo2_p05,
  percentile_cont(0.50) within group (order by e.spo2)        as spo2_median,
  percentile_cont(0.95) within group (order by e.spo2)        as spo2_p95
from public.drive_sessions s
join public.driver_profiles p on p.id = s.profile_id
left join public.telemetry_events e on e.session_id = s.id
group by s.id, p.display_name, p.custom_id;

-- --------------------------------------------------------------- baselines --
-- A driver's usual range, from every usable reading in their finished drives.
-- Needs >= 60 readings (one minute) before it is reported as established.
-- Mirrors lib/analysis/baseline.ts on the phone, which computes the same
-- thing offline for in-car alerts. Not a medical reference range.
-- dropped first: a later migration changes the columns, and
-- "create or replace view" cannot remove a column on a re-run.
drop view if exists public.driver_baselines;
create view public.driver_baselines
with (security_invoker = true) as
select
  s.profile_id,
  count(e.bpm)                                              as readings,
  count(distinct s.id)                                      as sessions,
  percentile_cont(0.10) within group (order by e.bpm)       as bpm_p10,
  percentile_cont(0.50) within group (order by e.bpm)       as bpm_median,
  percentile_cont(0.90) within group (order by e.bpm)       as bpm_p90,
  percentile_cont(0.10) within group (order by e.spo2)      as spo2_p10,
  percentile_cont(0.50) within group (order by e.spo2)      as spo2_median,
  count(e.bpm) >= 60                                        as established
from public.drive_sessions s
join public.telemetry_events e on e.session_id = s.id
where s.status = 'completed' and e.bpm is not null
group by s.profile_id;

-- Active right now: an open session whose phone checked in recently. A session
-- whose phone died without ending it drops off after 2 minutes on its own.
-- dropped first: a later migration changes the columns, and
-- "create or replace view" cannot remove a column on a re-run.
drop view if exists public.active_sessions;
create view public.active_sessions
with (security_invoker = true) as
select s.id as session_id, s.profile_id, p.display_name, p.custom_id,
       s.started_at, s.last_seen_at, s.link_state, s.storage_mode, s.sample_rate_hz
from public.drive_sessions s
join public.driver_profiles p on p.id = s.profile_id
where s.status = 'active'
  and s.last_seen_at > now() - interval '2 minutes';

-- ---------------------------------------------------------------- archives --
create table if not exists public.session_archives (
  session_id     uuid primary key references public.drive_sessions (id) on delete cascade,
  format         text    not null,               -- 'PPGA'
  format_version integer not null,               -- 1
  sample_rate_hz integer not null,
  sample_count   integer not null,
  frame_count    integer not null,
  raw_bytes      integer not null,               -- size before folding (samples as 2 x u32)
  packed_bytes   integer not null,               -- size of the .ppga file
  sha256         text    not null,               -- of the .ppga file; checked on unfold
  storage_path   text    not null,               -- object key in bucket 'session-archives'
  created_at     timestamptz not null default now()
);

alter table public.session_archives enable row level security;
drop policy if exists prototype_all on public.session_archives;
create policy prototype_all on public.session_archives
  for all to anon, authenticated using (true) with check (true);

-- Private bucket: objects are only reachable through the API with a key, never
-- by a public URL.
insert into storage.buckets (id, name, public)
values ('session-archives', 'session-archives', false)
on conflict (id) do nothing;

-- Prototype policies, same stance as the tables in schema.sql: the publishable
-- key may read and write archives. Replace with per-user policies before real
-- subject data (see docs/SYSTEM_GUIDE.md, "Security").
drop policy if exists "archives prototype read"   on storage.objects;
drop policy if exists "archives prototype insert" on storage.objects;
drop policy if exists "archives prototype update" on storage.objects;
create policy "archives prototype read" on storage.objects
  for select to anon, authenticated using (bucket_id = 'session-archives');
create policy "archives prototype insert" on storage.objects
  for insert to anon, authenticated with check (bucket_id = 'session-archives');
create policy "archives prototype update" on storage.objects
  for update to anon, authenticated using (bucket_id = 'session-archives')
  with check (bucket_id = 'session-archives');

-- ------------------------------------------------------------------ alerts --
-- Proposal alert-response flow: readings outside the driver's usual range for
-- a sustained period -> the phone prompts the driver (haptic + "Are you OK?")
-- -> "I'm OK" closes it; "Not well" or no answer in 30 s escalates. Escalation
-- is SIMULATED in this prototype (recorded, nobody is contacted), as the
-- proposal specifies for testing. Thresholds live in lib/analysis/alerts.ts.
create table if not exists public.drive_alerts (
  id            uuid primary key,
  session_id    uuid not null references public.drive_sessions (id) on delete cascade,
  kind          text not null,              -- 'bpm_high' | 'bpm_low' | 'spo2_low'
  value         numeric,                    -- 10-s median that triggered it
  threshold     numeric,                    -- the limit it crossed
  started_at    timestamptz not null,       -- first out-of-range reading
  prompted_at   timestamptz,                -- driver was asked
  response      text,                       -- 'ok' | 'unwell' | 'no_response' | null (open)
  responded_at  timestamptz,
  escalated     boolean not null default false,
  created_at    timestamptz not null default now()
);
create index if not exists idx_alerts_session on public.drive_alerts (session_id, started_at desc);
alter table public.drive_alerts enable row level security;
drop policy if exists prototype_all on public.drive_alerts;
create policy prototype_all on public.drive_alerts
  for all to anon, authenticated using (true) with check (true);

-- ---------------------------------------------------------------- realtime --
do $$
declare t text;
begin
  foreach t in array array['drive_sessions', 'telemetry_events', 'session_archives', 'drive_alerts'] loop
    if not exists (select 1 from pg_publication_tables
                   where pubname = 'supabase_realtime'
                     and schemaname = 'public' and tablename = t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- ------------------------------------------------ retire the live.sql bridge --
drop trigger  if exists mirror_to_test_readings on public.telemetry_events;
drop function if exists public.mirror_to_test_readings();

-- ------------------------------------------------------------- cleanup --
-- Rows the retired bridge copied from our automated SELFTEST drives while the
-- dashboard was being verified. Only those exact labels; the team's own
-- test_readings rows are untouched.
delete from public.test_readings where device_name in ('SELFTEST BPM', 'SELFTEST SpO2');


-- ===================================================================
-- v4_flags.sql
-- ===================================================================

-- Smart Wheel — v4: profile-aware flags and the voice check.
--
-- Run AFTER schema.sql, live.sql and v3_dashboard.sql (SQL Editor → New
-- query → paste → Run). Safe to re-run.
--
-- What this adds
--   * driver_profiles: conditions, medications (text arrays of the keys in
--     mobile-app/lib/analysis/profileModel.ts), voice-check language, and a
--     BMI the database computes itself from weight and height.
--     The emergency contact is intentionally NOT stored here: it stays on the
--     phone, which is what escalates.
--   * drive_alerts: level ('notice' | 'warning' | 'critical'), the channel the
--     driver answered through ('voice' | 'button' | 'none') and the answer
--     classifier's confidence. Transcripts are never uploaded.
--     `response` now also takes 'recovered' (the reading came back before
--     confirmation) and 'unconfirmed' (signal too poor to confirm), and
--     `kind` also 'no_contact' and 'irregular_rhythm'.

alter table public.driver_profiles add column if not exists conditions  text[] not null default '{}';
alter table public.driver_profiles add column if not exists medications text[] not null default '{}';
alter table public.driver_profiles add column if not exists language    text   not null default 'en';
alter table public.driver_profiles add column if not exists bmi numeric(4,1)
  generated always as (
    case when weight_kg > 0 and height_cm > 0
         then round(weight_kg / ((height_cm / 100.0) * (height_cm / 100.0)), 1)
    end
  ) stored;

alter table public.drive_alerts add column if not exists level             text;
alter table public.drive_alerts add column if not exists channel           text;
alter table public.drive_alerts add column if not exists answer_confidence numeric;

create index if not exists idx_alerts_level on public.drive_alerts (level, started_at desc);


-- ===================================================================
-- v5_delete.sql
-- ===================================================================

-- Smart Wheel — v5: let the app delete what it uploaded.
--
-- Run after v4_flags.sql (SQL Editor → New query → paste → Run). Safe to re-run.
--
-- The tables already allow deletes (prototype_all policy in schema.sql /
-- v3_dashboard.sql, and ON DELETE CASCADE from driver_profiles down to
-- drive_sessions, telemetry_events, drive_alerts and session_archives). What
-- was missing is permission to remove the waveform archive files from
-- Storage, so a deleted driver's .ppga files would otherwise stay behind.
--
-- Prototype policy, same stance as the others: replace with per-user policies
-- before real subject data (docs/SYSTEM_GUIDE.md, "Security").

drop policy if exists "archives prototype delete" on storage.objects;
create policy "archives prototype delete" on storage.objects
  for delete to anon, authenticated using (bucket_id = 'session-archives');


-- ===================================================================
-- v6_quality.sql
-- ===================================================================

-- Smart Wheel — v6: per-second signal-quality labels and personal calibration.
--
-- Run after v5_delete.sql (SQL Editor → New query → paste → Run). Safe to re-run.
--
-- Every reading now carries the phone's own analysis of the 100 Hz waveform
-- (mobile-app/lib/analysis/signal.ts), so the dataset says how trustworthy
-- each second was:
--   hr_beats    heart rate from the individual beats (independent of the ESP32)
--   sqi_good    clean pulse (Orphanidou 2015 feasibility + template match)
--               AND the two heart-rate estimates agree
--   template_r  mean beat-to-template correlation (0..1)
--   perfusion   perfusion index, AC/DC × 100 (%)
--   skewness    skewness of the band-passed window (Elgendi 2016 SQI)
-- Personal calibration against a reference device (see the guide, §11):
--   cal_hr / cal_spo2   bounded offsets applied by the phone; cal_at when set.

alter table public.telemetry_events add column if not exists hr_beats   numeric(5,1);
alter table public.telemetry_events add column if not exists sqi_good   boolean;
alter table public.telemetry_events add column if not exists template_r numeric(4,3);
alter table public.telemetry_events add column if not exists perfusion  numeric(6,3);
alter table public.telemetry_events add column if not exists skewness   numeric(6,3);

alter table public.driver_profiles add column if not exists cal_hr   numeric(4,1);
alter table public.driver_profiles add column if not exists cal_spo2 numeric(4,1);
alter table public.driver_profiles add column if not exists cal_at   timestamptz;

-- Baselines from clean seconds only: the view now ignores readings the phone
-- judged unreliable (sqi_good = false). Rows from older app versions have no
-- label (null) and still count.
-- dropped first: a later migration changes the columns, and
-- "create or replace view" cannot remove a column on a re-run.
drop view if exists public.driver_baselines;
create view public.driver_baselines
with (security_invoker = true) as
select
  s.profile_id,
  count(e.bpm)                                              as readings,
  count(distinct s.id)                                      as sessions,
  percentile_cont(0.10) within group (order by e.bpm)       as bpm_p10,
  percentile_cont(0.50) within group (order by e.bpm)       as bpm_median,
  percentile_cont(0.90) within group (order by e.bpm)       as bpm_p90,
  percentile_cont(0.10) within group (order by e.spo2)      as spo2_p10,
  percentile_cont(0.50) within group (order by e.spo2)      as spo2_median,
  count(e.bpm) >= 60                                        as established
from public.drive_sessions s
join public.telemetry_events e on e.session_id = s.id
where s.status = 'completed' and e.bpm is not null and e.sqi_good is not false
group by s.profile_id;


-- ===================================================================
-- v7_history.sql
-- ===================================================================

-- Smart Wheel — v7: adaptation history.
--
-- Run after v6_quality.sql (SQL Editor → New query → paste → Run). Safe to re-run.
--
-- One row each time the phone recomputes a driver's thresholds and they
-- changed (after a drive, an "I'm OK" answer, a profile edit, a reset), so
-- the team can see the system learning each driver over time: how much it
-- relies on their own data (learned 0..1), their expected heart rate
-- (mean ± sd) and the warning lines themselves.

create table if not exists public.threshold_history (
  id          uuid primary key,
  profile_id  uuid not null references public.driver_profiles (id) on delete cascade,
  at          timestamptz not null,
  reason      text not null,          -- 'drive' | 'ok_answer' | 'profile' | 'reset'
  drives      integer not null,
  learned     numeric(4,3) not null,
  mean        numeric(5,1) not null,
  sd          numeric(4,1) not null,
  high_warn   integer not null,
  low_warn    integer not null,
  spo2_warn   integer not null
);
create index if not exists idx_history_profile on public.threshold_history (profile_id, at);

alter table public.threshold_history enable row level security;
drop policy if exists prototype_all on public.threshold_history;
create policy prototype_all on public.threshold_history
  for all to anon, authenticated using (true) with check (true);

commit;

-- What you should have now (run this to check):
select table_name, table_type from information_schema.tables
 where table_schema = 'public'
   and table_name in ('driver_profiles','drive_sessions','telemetry_events',
                      'session_archives','drive_alerts','threshold_history',
                      'session_summaries','driver_baselines','active_sessions',
                      'test_readings')
 order by table_type, table_name;
