#!/usr/bin/env python3
"""Concatenates the migrations, in order, into apply_all.sql.

Keeps one file to run on a fresh database instead of seven, and cannot drift
from the sources because it is generated.

    python3 build_apply_all.py
"""
from datetime import date
from pathlib import Path

ORDER = ["schema.sql", "live.sql", "v3_dashboard.sql", "v4_flags.sql",
         "v5_delete.sql", "v6_quality.sql", "v7_history.sql"]
HERE = Path(__file__).parent

head = f"""-- Smart Wheel - APPLY EVERYTHING (Team 18, generated {date.today()})
--
-- Brings a database to exactly the state the app and the website expect.
-- It is the seven migrations, in order, in one file:
--   {' -> '.join(f.replace('.sql', '') for f in ORDER)}
--
-- Safe to run on a database that already has some or all of it: every
-- statement is written to be re-runnable (create ... if not exists, create or
-- replace, drop policy ... if exists before create).
--
-- It does NOT touch public.test_readings, the team's original table.
--
-- How to run: Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
-- Generated by build_apply_all.py; edit the migrations, not this file.

begin;
"""
parts = [head]
for name in ORDER:
    body = (HERE / name).read_text().rstrip()
    parts.append(f"\n\n-- ===================================================================\n"
                 f"-- {name}\n"
                 f"-- ===================================================================\n\n{body}\n")
parts.append("""
commit;

-- What you should have now (run this to check):
select table_name, table_type from information_schema.tables
 where table_schema = 'public'
   and table_name in ('driver_profiles','drive_sessions','telemetry_events',
                      'session_archives','drive_alerts','threshold_history',
                      'session_summaries','driver_baselines','active_sessions',
                      'test_readings')
 order by table_type, table_name;
""")
out = HERE / "apply_all.sql"
out.write_text("".join(parts))
print(f"wrote {out} ({len(out.read_text().splitlines())} lines from {len(ORDER)} migrations)")
