-- Smart Wheel - LEGACY COMPATIBILITY for branch samantha/mobile-app-setup
-- (JosselinPonce/FIU-SeniorDesign, head dbf8c09 "Add in-app vitals demo mode")
--
-- Makes the database serve that older app. Run it:
--   * on the current database, to let the old app work alongside ours
--     (nothing is dropped, no data is lost), or
--   * after revert_all.sql, to rebuild what the old app needs from scratch.
--
-- WHAT THE OLD APP TOUCHES, taken from its source, not from guesswork:
--   public.test_readings   App.tsx        insert {value, device_name}
--   public.driver_profiles lib/profiles.ts
--                          select id, display_name, age, height_cm, weight_kg,
--                                 gender, emergency_contact_name,
--                                 emergency_contact_phone
--                          insert WITHOUT id  -> the column needs a default
--                          gender is free text -> no CHECK constraint allowed
--   public.telemetry_events lib/monitoring.ts
--                          realtime INSERT feed; reads id, session_id,
--                          event_type, bpm, spo2, signal_quality, received_at
--   public.incidents       lib/monitoring.ts insert {telemetry_event_id,
--                          session_id, heart_rate, spo2, status, severity,
--                          driver_reply, response, action,
--                          asked_emergency_call, call_placed}
--
-- Safe to re-run, and safe on a database that already has our schema: it only
-- adds columns, defaults and tables, and relaxes one constraint.
--
-- How to run: Supabase dashboard -> SQL Editor -> New query -> paste -> Run.

begin;

-- 1. The team's original test table (created here only if it is missing).
create table if not exists public.test_readings (
  id          bigint generated by default as identity primary key,
  value       numeric,
  device_name text,
  created_at  timestamptz not null default now()
);

-- 2. Driver profiles. The table may already exist with our columns; these
--    statements bring it up to what the old app expects either way.
create table if not exists public.driver_profiles (
  id           uuid primary key default gen_random_uuid(),
  display_name text not null,
  created_at   timestamptz not null default now()
);
alter table public.driver_profiles alter column id set default gen_random_uuid();
alter table public.driver_profiles add column if not exists age        integer;
alter table public.driver_profiles add column if not exists height_cm  numeric(5,2);
alter table public.driver_profiles add column if not exists weight_kg  numeric(5,2);
alter table public.driver_profiles add column if not exists gender     text;
alter table public.driver_profiles add column if not exists emergency_contact_name  text;
alter table public.driver_profiles add column if not exists emergency_contact_phone text;
-- The old app saves whatever the driver types into the gender field, while our
-- schema restricts it to four values. Drop the constraint: our own app only
-- ever writes the allowed values, so nothing of ours depends on it.
alter table public.driver_profiles drop constraint if exists driver_profiles_gender_check;

-- 3. Drive sessions and telemetry. The old app subscribes to telemetry inserts
--    and reads the columns below; these definitions match our schema, so on
--    the current database nothing changes.
create table if not exists public.drive_sessions (
  id         uuid primary key default gen_random_uuid(),
  profile_id uuid references public.driver_profiles (id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at   timestamptz,
  status     text not null default 'active'
);
create table if not exists public.telemetry_events (
  id              uuid primary key default gen_random_uuid(),
  session_id      uuid not null references public.drive_sessions (id) on delete cascade,
  sequence_number integer,
  event_type      text not null,
  bpm             integer,
  spo2            integer,
  signal_quality  integer,
  battery         integer,
  received_at     timestamptz not null default now(),
  uploaded_at     timestamptz not null default now()
);
alter table public.telemetry_events alter column id set default gen_random_uuid();

-- 4. Incidents: what the voice agent said and did. Only the old app uses this
--    table; our app records the same events in public.drive_alerts.
create table if not exists public.incidents (
  id                   uuid primary key default gen_random_uuid(),
  telemetry_event_id   uuid,
  session_id           uuid,
  heart_rate           integer,
  spo2                 integer,
  status               text,
  severity             text,
  driver_reply         text,
  response             text,
  action               text,
  asked_emergency_call boolean not null default false,
  call_placed          boolean not null default false,
  created_at           timestamptz not null default now()
);
create index if not exists idx_incidents_session on public.incidents (session_id, created_at desc);

-- 5. Realtime: the old app's alerts depend on telemetry inserts being
--    broadcast. (Our live.sql does the same; this is here for the case where
--    revert_all.sql has been run.)
do $$
declare t text;
begin
  foreach t in array array['drive_sessions', 'telemetry_events', 'incidents'] loop
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (select 1 from pg_publication_tables
                       where pubname = 'supabase_realtime'
                         and schemaname = 'public' and tablename = t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- 6. Prototype access: the app signs in with the anon key only. Same open
--    policy the rest of this project uses. NOT for real patient data.
do $$
declare t text;
begin
  foreach t in array array['test_readings', 'driver_profiles', 'drive_sessions',
                           'telemetry_events', 'incidents'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists prototype_all on public.%I', t);
    execute format('create policy prototype_all on public.%I for all to anon, authenticated '
                   'using (true) with check (true)', t);
  end loop;
end $$;

commit;

-- Check: every table the old app needs should be listed here.
select table_name from information_schema.tables
 where table_schema = 'public'
   and table_name in ('test_readings','driver_profiles','drive_sessions',
                      'telemetry_events','incidents')
 order by table_name;
