// Proves the Supabase scripts do what they claim, on real Postgres
// (PGlite = Postgres 18 compiled to WebAssembly, no server to install).
//
//   cd mobile-app && npm i -D @electric-sql/pglite && npm run test:sql
//
// Three scenarios, each on a fresh database that starts the way the team's
// did (their test_readings table, the storage schema, the realtime
// publication, the anon/authenticated roles):
//
//   A  apply_all twice -> use the app's tables and views -> revert_all twice,
//      and the database is back to the original object and policy list.
//   B  apply_all -> legacy_samantha: the OLD app's own queries run, and ours
//      still work. This is the "both apps on one database" case.
//   C  apply_all -> revert_all -> legacy_samantha: the OLD app's queries run
//      on a database rolled all the way back. This is the "go back to the old
//      version" case.
//
// The old app's queries are copied from branch samantha/mobile-app-setup
// (App.tsx, lib/profiles.ts, lib/monitoring.ts), not invented here.
import { PGlite } from '@electric-sql/pglite'
import { readFileSync } from 'node:fs'

const SQL = new URL('.', import.meta.url).pathname
const read = (f) => readFileSync(`${SQL}/${f}`, 'utf8')
const fails = []
const check = (name, ok, detail = '') => {
  console.log(`   ${ok ? 'PASS' : 'FAIL'}  ${name}${ok || !detail ? '' : ' -> ' + detail}`)
  if (!ok) fails.push(name)
}

async function freshDb(protectStorage = false) {
  const db = await PGlite.create()
  await db.exec(`
    create role anon; create role authenticated;
    create schema storage;
    create table storage.buckets (id text primary key, name text, public boolean);
    create table storage.objects (id serial primary key, bucket_id text, name text);
    alter table storage.objects enable row level security;
    create publication supabase_realtime;
    create table public.test_readings (
      id bigint generated by default as identity primary key,
      value numeric, device_name text,
      created_at timestamptz not null default now());
    insert into public.test_readings (value, device_name) values (72, 'team bench');
  `)
  if (protectStorage) {
    // What Supabase does on newer projects: a trigger refuses direct deletes
    // from the storage tables ("Use the Storage API instead").
    await db.exec(`
      create function storage.protect_delete() returns trigger language plpgsql as $$
      begin
        raise exception 'Direct deletion from storage tables is not allowed. Use the Storage API instead.'
          using errcode = '42501';
      end $$;
      create trigger protect_objects before delete on storage.objects
        for each statement execute function storage.protect_delete();
      create trigger protect_buckets before delete on storage.buckets
        for each statement execute function storage.protect_delete();`)
  }
  return db
}
const q = (db) => async (s) => (await db.query(s)).rows
const objects = async (db) => (await q(db)(`select table_name n, table_type t
  from information_schema.tables where table_schema='public' order by 1`))
  .map(r => `${r.t === 'VIEW' ? 'view' : 'table'} ${r.n}`)
const policies = async (db) => (await q(db)(
  `select schemaname||'.'||tablename||': '||policyname p from pg_policies order by 1`)).map(r => r.p)
const run = async (db, file, label) => {
  try { await db.exec(read(file)); return true }
  catch (e) { check(`${label} (${file})`, false, e.message); return false }
}

// Our app's own use: it supplies UUIDs itself and reads the summary views.
async function ourAppWorks(db, tag) {
  const Q = q(db)
  try {
    await db.exec(`
      insert into public.driver_profiles (id, custom_id, display_name, weight_kg, height_cm)
        values ('11111111-1111-1111-1111-111111111111', 'luis', 'Luis', 80, 180)
        on conflict (id) do nothing;
      insert into public.drive_sessions (id, profile_id, started_at, status)
        values ('22222222-2222-2222-2222-222222222222',
                '11111111-1111-1111-1111-111111111111', now(), 'completed')
        on conflict (id) do nothing;
      insert into public.telemetry_events
        (id, session_id, event_type, received_at, sequence_number, bpm, spo2, finger, quality, sqi_good)
        values (gen_random_uuid(), '22222222-2222-2222-2222-222222222222', 'vitals', now(), 1, 72, 98, true, 90, true)
        on conflict do nothing;`)
    const s = await Q('select count(*)::int n from public.session_summaries')
    const b = await Q('select count(*)::int n from public.driver_baselines')
    check(`${tag}: our app inserts and reads its views`, s[0].n >= 1 && b[0].n >= 1)
  } catch (e) { check(`${tag}: our app inserts and reads its views`, false, e.message) }
}

// The old app's queries, as that branch writes them.
async function oldAppWorks(db, tag) {
  const Q = q(db)
  try {
    // App.tsx: send a test reading
    await db.exec(`insert into public.test_readings (value, device_name) values (77, 'test-iphone');`)
    // lib/profiles.ts: save a profile with NO id, and free-text gender
    const prof = await Q(`insert into public.driver_profiles
      (display_name, age, height_cm, weight_kg, gender, emergency_contact_name, emergency_contact_phone)
      values ('Samantha', 22, 165, 60, 'Female', 'Mom', '+13055550123')
      returning id, display_name, age, height_cm, weight_kg, gender,
                emergency_contact_name, emergency_contact_phone`)
    check(`${tag}: old app saves a profile without an id, free-text gender`,
          prof.length === 1 && prof[0].gender === 'Female')
    // lib/profiles.ts: load the list with its exact column set
    await Q(`select id, display_name, age, height_cm, weight_kg, gender,
                    emergency_contact_name, emergency_contact_phone
               from public.driver_profiles order by id`)
    // lib/monitoring.ts: a vitals event arrives, then an incident is logged
    const sess = await Q(`insert into public.drive_sessions (id, profile_id, started_at, status)
      values (gen_random_uuid(), '${prof[0].id}', now(), 'active') returning id`)
    const ev = await Q(`insert into public.telemetry_events
      (session_id, event_type, received_at, bpm, spo2, signal_quality)
      values ('${sess[0].id}', 'vitals', now(), 132, 91, 80) returning id, session_id, event_type, bpm, spo2, signal_quality, received_at`)
    check(`${tag}: old app reads a telemetry row with its column set`, ev.length === 1 && ev[0].bpm === 132)
    await db.exec(`insert into public.incidents
      (telemetry_event_id, session_id, heart_rate, spo2, status, severity,
       driver_reply, response, action, asked_emergency_call, call_placed)
      values ('${ev[0].id}', '${sess[0].id}', 132, 91, 'HIGH_HR', 'warning',
              'I am fine', 'Keep an eye on it', 'log', false, false);`)
    const inc = await Q(`select count(*)::int n from public.incidents`)
    check(`${tag}: old app logs an incident`, inc[0].n >= 1)
    const pub = await Q(`select count(*)::int n from pg_publication_tables
      where pubname='supabase_realtime' and tablename='telemetry_events'`)
    check(`${tag}: telemetry inserts are broadcast for the old app's alerts`, pub[0].n === 1)
  } catch (e) { check(`${tag}: old app queries`, false, e.message) }
}

// ---------------------------------------------------------------- A -------
console.log('\nA. apply_all -> use -> revert_all, twice each')
{
  const db = await freshDb()
  const before = { obj: await objects(db), pol: await policies(db) }
  for (const pass of [1, 2]) if (!await run(db, 'apply_all.sql', `apply pass ${pass}`)) break
  check('A: our tables and views exist', (await objects(db)).length === 10)
  await ourAppWorks(db, 'A')
  await db.exec(`insert into storage.buckets (id,name,public) values ('other','other',false) on conflict do nothing;
                 insert into storage.objects (bucket_id,name) values ('session-archives','a.ppga');`)
  for (const pass of [1, 2]) if (!await run(db, 'revert_all.sql', `revert pass ${pass}`)) break
  const end = { obj: await objects(db), pol: await policies(db) }
  check('A: objects back to the original list', JSON.stringify(end.obj) === JSON.stringify(before.obj),
        JSON.stringify(end.obj))
  check('A: policies back to the original list', JSON.stringify(end.pol) === JSON.stringify(before.pol))
  const t = await q(db)(`select count(*)::int n from public.test_readings`)
  check("A: the team's test_readings kept", t[0].n === 1)
  const bk = await q(db)(`select count(*)::int n from storage.buckets where id='session-archives'`)
  const fl = await q(db)(`select count(*)::int n from storage.objects where bucket_id='session-archives'`)
  const ot = await q(db)(`select count(*)::int n from storage.buckets where id='other'`)
  check('A: archive bucket and its files removed', bk[0].n === 0 && fl[0].n === 0)
  check('A: other storage buckets untouched', ot[0].n === 1)
}

// ---------------------------------------------------------------- B -------
console.log('\nB. current schema + legacy script: both apps on one database')
{
  const db = await freshDb()
  await run(db, 'apply_all.sql', 'apply')
  await run(db, 'legacy_samantha.sql', 'legacy')
  await ourAppWorks(db, 'B')
  await oldAppWorks(db, 'B')
  await run(db, 'legacy_samantha.sql', 'legacy re-run')
  check('B: legacy script is safe to re-run', true)
}

// ---------------------------------------------------------------- C -------
console.log('\nC. rolled all the way back, then the legacy script')
{
  const db = await freshDb()
  await run(db, 'apply_all.sql', 'apply')
  await run(db, 'revert_all.sql', 'revert')
  await run(db, 'legacy_samantha.sql', 'legacy')
  await oldAppWorks(db, 'C')
  const ours = await q(db)(`select count(*)::int n from information_schema.tables
    where table_schema='public' and table_name in ('drive_alerts','threshold_history','session_archives')`)
  check('C: our extra tables are gone', ours[0].n === 0)
}

// ---------------------------------------------------------------- D -------
console.log("\nD. revert on a project where Supabase protects the storage tables")
{
  const db = await freshDb(true)
  await run(db, 'apply_all.sql', 'apply')
  await db.exec(`insert into storage.objects (bucket_id, name) values ('session-archives','a.ppga');`)
  const ok = await run(db, 'revert_all.sql', 'revert with protected storage')
  check('D: revert still completes when the storage delete is refused', ok)
  const left = await q(db)(`select count(*)::int n from information_schema.tables
    where table_schema='public' and table_name in
      ('driver_profiles','drive_sessions','telemetry_events','drive_alerts',
       'session_archives','threshold_history')`)
  check('D: our tables are gone anyway', left[0].n === 0, `${left[0].n} left`)
  const pol = await q(db)(`select count(*)::int n from pg_policies
    where schemaname='storage' and policyname like 'archives prototype%'`)
  check('D: our storage policies are gone', pol[0].n === 0)
  const bk = await q(db)(`select count(*)::int n from storage.buckets where id='session-archives'`)
  check('D: the bucket survives, to be removed with the Storage API', bk[0].n === 1)
}

// ---------------------------------------------------------------- E -------
console.log('\nE. legacy schema FIRST, then apply_all (what happens after a rollback)')
{
  const db = await freshDb()
  await run(db, 'legacy_samantha.sql', 'legacy')
  await oldAppWorks(db, 'E-before')
  const ok = await run(db, 'apply_all.sql', 'apply on top of the legacy schema')
  check('E: apply_all runs on a legacy-shaped database', ok)
  const cols = await q(db)(`select count(*)::int n from information_schema.columns
    where table_schema='public' and table_name='driver_profiles' and column_name='custom_id'`)
  check('E: driver_profiles gained our columns', cols[0].n === 1)
  await ourAppWorks(db, 'E')
  await oldAppWorks(db, 'E-after')
  await run(db, 'apply_all.sql', 'apply again')
  check('E: still re-runnable afterwards', true)
}

console.log(`\n${fails.length ? fails.length + ' CHECK(S) FAILED: ' + fails.join('; ') : 'ALL CHECKS PASSED'}`)
process.exit(fails.length ? 1 : 0)
